
dependencies:
- python=3.6.8
- pip:
  - azureml-core==1.18.0.post1
  - azureml-defaults==1.18.0
  - azureml-telemetry==1.18.0
  - azureml-train-restclients-hyperdrive==1.18.0
  - azureml-train-core==1.18.0
  - cmake
  - torch
  - mkl
  - future
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - torchtext
  - azureml-mlflow
  - mlflow
  - azureml-contrib-fairness
  - fairlearn
